- name: RPi Applications Playbook
  hosts: all
  tasks:
  - name: Check if CGroup is configured
    ansible.builtin.shell: cat /boot/cmdline.txt
    register: cmdline
    changed_when: false

  - name: CGroup commands
    become: yes
    ansible.builtin.replace:
      path: /boot/cmdline.txt
      regexp: "\n"
      replace: " cgroup_memory=1 cgroup_enable=memory\n"
    when: "'cgroup_memory=1 cgroup_enable=memory' not in cmdline.stdout"

  - name: Check if K3S is installed
    become: yes
    ansible.builtin.shell: find / -type d -name k3s
    register: k3s
    changed_when: false

  - name: Install K3S
    shell: curl -sfL https://get.k3s.io | sh -
    when: k3s.stdout == ""
