- name: RPi Applications Playbook
  hosts: all
  tasks:
  - name: CGroup commands
    become: yes
    ansible.builtin.replace:
      path: /boot/cmdline.txt
      regexp: "\n"
      replace: ' cgroup_memory=1 cgroup_enable=memory\n'

  - name: Install K3S
    shell: curl -sfL https://get.k3s.io | sh -
